name: Publish to npm

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile

      - run: yarn build:lib

      - run: npm publish --access public --provenance
        working-directory: packages/fetch-stream-audio
